export const skills = [
  {
    level: "Good at",
    description: "Things that I can do very well and want to do daily",
    skills: [
      "React",
      "Vue",
      "Svelte",
      "Solid",
      "Typescript",
      // "WebView",
      "Storybook",
      // "Tauri",
      "Tailwind",
      "SASS",
      "Vite",
      "Node",
      "Git",
      // "UnoCSS",
      // "Interaction design",
      "i18n",
      "APIs"
      // "DX",
      // "VR development",
    ],
  },
  {
    level: "Learning",
    description: "Things I want to do daily but still have a lot to learn",
    skills: [
      "Rust",
      "Deno",
      "Cypress",
      "Prisma",
      // "Zod",
      "Linux",
      "Nix",
      "Docker",
      "Backend",
      // "Bevy",
      // "Shaders",
      "Documentation",
      // "Open-source",
      "a11y",
      "DevOps",
    ],
  },
  {
    level: "Other experience",
    description: "Hobbies and things I tried",
    skills: [
      "UI design",
      "Web design",
      "UX",
      // "Nuxt",
      "Game development",
      "React Native",
      "Strapi CMS",
      "Firebase",
      "Jest",
      // "Webpack",
      "Electron",
      "Java",
      "C#",
      // "Unity",
      // "WordPress",
    ],
  }
];

export default skills;
