export const skills = [
  {
    level: "Good at",
    description: "Things that I can do very well and want to do daily",
    skills: [
      "Node",
      "Typescript",
      "WebView",
      "Vite",
      "Solid JS",
      "Tauri",
      "Git",
      "Tailwind",
      "UnoCSS",
      // "UI design",
      // "Interaction design",
      "Internationalization",
      "DX",
      // "VR development",
    ],
  },
  {
    level: "Learning",
    description: "Things I want to do daily but still have a lot to learn",
    skills: [
      "Deno",
      "Rust",
      "Backend",
      "Prisma",
      "Bevy",
      "Shaders",
      "Documentation",
      "Open-source",
      "User research",
      "Linux",
      "Nix",
      "Docker",
    ],
  },
  {
    level: "Past experience",
    description: "Things I can do well but have found better alternatives",
    skills: [
      "Svelte",
      "Vue",
      "Nuxt",
      "React",
      "React Native",
      "Jest",
      "Webpack",
      "Electron",
      "Java",
      "C#",
      "Unity",
      // "WordPress",
    ],
  }
];

export default skills;
